### ISSUE TITLE
Very slow on long lists

### ISSUE THREAD

**Issue by nijel** [wemake-services/flake8-eradicate#176]
It takes ages to check a file with very long statement (for example https://github.com/WeblateOrg/language-data/blob/master/weblate_language_data/check_languages.py takes minute and half to check).

The problem seems to be in:

https://github.com/sobolevn/flake8-eradicate/blob/a9866301eb145be5b2f17ae58532b549d97c53a0/flake8_eradicate.py#L126-L129

The _tokens accumulate until the statement parsing is complete and flake8-eradicate checks all the tokens in the list for every line.

**Comment by sobolevn** [comment]
@nijel PRs are welcome! I would love to release a version with the fix.

**Comment by nijel** [comment]
Unfortunately, my knowledge of flake8 plugins is exactly zero, otherwise the PR would be already there...
