### ISSUE TITLE
Detects "# TODO: ..." as commented out code

### ISSUE THREAD

**Issue by phyrwork** [wemake-services/flake8-eradicate#177]
And other similar annotations with the pattern "# LABEL: detail".

It appears to be mistaking a legitimate comment for code containing a variable with type annotation.

I don't think it's appropriate to have to noqa every TODO or FIXME (unless they break a rule from somewhere else, of course).

Maybe there could be a whitelist of common labels that won't get picked up as a variable?

**Comment by sobolevn** [comment]
Thanks for the suggestion! Please, reopen at https://github.com/myint/eradicate
