### ISSUE TITLE
Compat with flake8 >= 6

### ISSUE THREAD

**Issue by g-as** [wemake-services/flake8-eradicate#269]
Notably, flake8 bumped min python version to 3.8.1

https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html

I can draft a PR based on what you want to do, either:
- minimal changes increasing flake8's upper bound
- big changes with a 2.0, aligning with flake8 in supporting >= 3.8.1, 3.11 support

**Comment by sobolevn** [comment]
See https://github.com/wemake-services/flake8-broken-line/pull/280

**Comment by janmayer** [comment]
Could you just drop the upper bond? We see that the flake8 team release major versions quite regularly - without these versions requiring any change to the extensions.

This is the only flake8 extensions we use that breaks the build every time on a flake8 major version bump.

**Comment by osherdp** [comment]
For us as well (only this plugin has an upper-bound version restriction):
```
The conflict is caused by:
    The user requested flake8==6.0.0
    flake8-bugbear 22.10.27 depends on flake8>=3.0.0
    flake8-formatter-junit-xml 0.0.6 depends on flake8>3.0.0
    flake8-colors 0.1.9 depends on flake8>3.0.0
    flake8-eradicate 1.4.0 depends on flake8<6 and >=3.5
```

**Comment by zerocewl** [comment]
yep, same here:

```console
    The conflict is caused by:
        The user requested flake8 6.0.0 (from /builds/...)
        flake8-annotations-complexity 0.0.7 depends on flake8
        flake8-bugbear 22.9.23 depends on flake8>=3.0.0
        flake8-builtins 1.5.3 depends on flake8
        flake8-docstrings 1.6.0 depends on flake8>=3
        flake8-eradicate 1.4.0 depends on flake8<6 and >=3.5
```

**Comment by zerocewl** [comment]
see changes from @danyeaw https://github.com/wemake-services/flake8-eradicate/pull/271

**Comment by tekdj7** [comment]
@sobolevn @mkniewallner this plug-in is very helpful ensuring comments aren't left behind when code goes to production.  Any update on when this can be fixed so eradicate can work with flake8 6+?

**Comment by mkniewallner** [comment]
> @sobolevn @mkniewallner this plug-in is very helpful ensuring comments aren't left behind when code goes to production. Any update on when this can be fixed so eradicate can work with flake8 6+?

I am not a maintainer of this repository, please don't ping me.

**Comment by zerocewl** [comment]
@sobolevn
Is this repo still maintained?
otherwise we might create a simple clone for the needed updates?

**Comment by Victoremepunto** [comment]
bump

**Comment by hoefling** [comment]
Just as a small heads-up, I replaced `flake8-eradicate` and a bunch of other plugins with [`ruff`](https://github.com/charliermarsh/ruff), which is also a lot faster than running `flake8`. The replacement in config is simply turning the `"ERA"` rules group on in `pyproject.toml`:
```toml
[tool.ruff]
select = ["ERA", ...]
```
The minimal addition to `.pre-commit-config.yaml` is
```yaml
repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.257
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
```
I didn't drop `flake8` completely yet, with both tools running alongside for now, but the more I use `ruff`, the less I want to look back TBH.
